### ISSUE TITLE
“reverse” setting of ZWO EAF driver not inherited

### ISSUE THREAD

**Issue by limburg11** [jlecomte/ascom-virtual-focuser#1]
When I use 2 telescope setups with EAFs, one with “reverse” set and one with “reverse” unset, I have to correct the “reverse” setting manually in the original ZWO driver, as it is not saved in the Virtual Driver. I’m using N.I.N.A. with 2 different profiles, and it would be great if the “reverse” setting was saved in the NINA profiles as part of the Virtual Focuser’s settings.

Regards, Bernd

**Comment by jlecomte** [comment]
Hi @limburg11 , thank you for reporting this issue! The reverse setting you are referring to, is it a checkbox in the EAF driver options dialog? If so, I don't understand how that would even work, even without this virtual focuser driver in the middle. There is no "reverse" property in the `IFocuserV3` ASCOM interface. The virtual focuser driver simply forwards the position that the application (NINA in your case) wants the focuser to move to. Can you share a few screenshots? Maybe I am missing something obvious. Also, are you saying that what you are doing works fine if you don't use the virtual focuser driver? Thanks!

**Comment by limburg11** [comment]
Hi Julien, yes, the reverse setting is a checkbox in the EAF driver options dialog, see attached image:
![5D274CD4-2D85-4C7B-8EB6-863E63DA696C_4_5005_c](https://user-images.githubusercontent.com/77612997/218141866-a1b51b19-45dc-4a40-bc84-ae8141df1418.jpeg)

But you are completely right, this checkbox must be set within this dialog and nowhere else. The problem was that this dialog didn't distinguish between my different EAFs because they all had the same name ("EAF(EAF)"). But this name can be edited, and now each of my motors has a unique name and the setup dialog assigns the individual setting to the correct device.

So, all is working perfectly without the need for any change in the Virtual Focuser.

Thanks, Bernd

**Comment by jlecomte** [comment]
Awesome, thank you for confirming!
