### ISSUE TITLE
ASCOM Driver Error

### ISSUE THREAD

**Issue by bobbryant** [jlecomte/ascom-virtual-focuser#5]
I have a ZWO EAF and have been using NINA for temperature focus compensation since you introduced your virtual driver.  I installed the new driver version 1.2.1, and it worked as before when using the ZWO temperature sensor.  But when I select the Pegasus Astro PPBAdvance and click the power icon I get "ASCOM Driver Error Unable to connect to DarkSkyGreek's Virtual Focuser Ascom Driver.  Reason: Cannot connect to ASCOM.EAF.focurser".   Switching back to the ZWO Focuser (1) as the source for temperature and focuser connects.

Bob Bryant bob.bryant@pobox.com

**Comment by jlecomte** [comment]
Workaround documented in [this commit](https://github.com/jlecomte/ascom-virtual-focuser/commit/79b45b81f3ae12e85b62a05e57b97bcb5f1c7a4b). Will keep this issue open until I can find a more permanent and user-friendly fix.

**Comment by jlecomte** [comment]
Fixed once and for all in v1.2.2 (better error handling and updated instructions to be more precise)
